name: darya-ds
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pycodestyle
  - pylint
  - python-dotenv
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - easyocr
  - pip:
    - deep_translator
